### ISSUE TITLE
Integrate UpdaterTest from parse-composer

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-packagist#13] opened 2015-01-21 18:38 UTC
We remove the UpdaterTest from parse-composer to simplify the dependencies graph. Lets add it to drupal-packagist again.

Related PR: drupal-composer/drupal-parse-composer#10

**Comment by derhasi** [comment] 2015-01-21 18:39
Duplicate of #12

**Closed as completed by derhasi** 2015-01-21 18:39 UTC
Labels: duplicate
