### ISSUE TITLE
drupal/entityqueue requires drupal/system which is not a real package

### ISSUE THREAD

**Issue by davidbarratt** [drupal-composer/drupal-packagist#31] opened 2015-05-04 14:44 UTC
I just noticed that [drupal/entityqueue](https://packagist.drupal-composer.org/packages/drupal/entityqueue) requires `drupal/system` which is not a real package.

**Comment by webflo** [comment] 2015-05-04 16:39
Thats correct, but drupal/system is part of drupal/drupal. I think this is not a bug. Currently is it required that you add drupal/drupal to your root composer json.

**Comment by webflo** [comment] 2015-05-04 16:41
#15 should fix this in the long run.

**Comment by webflo** [comment] 2016-04-02 14:41
Closed in favour of #15

**Closed as completed by webflo** 2016-04-02 14:41 UTC
