### ISSUE TITLE
Need guide about contributing

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-packagist#7] opened 2015-01-21 09:15 UTC
_From @dutchiexl on December 24, 2014 8:55_

Sometimes I hit a wrong configured package, or a package is missing. Would contributers be able to add and change these ? Is it possible to add a "guide" here somewhere ?

_Copied from original issue: webflo/packagist#7_

**Comment by webflo** [comment] 2015-01-21 09:15
_From @kasperg on December 24, 2014 9:10_

If a package is missing or misconfigured it is probably due to a bug in the project.

Unlike packagist.org this fork retrieves projects from drupal.org using the API and exposes them as Composer packages. Contributors should only need to worry about getting their projects on drupal.org.

There are probably a lot of edge cases so getting a list of problematic projects would be a great start.

**Comment by webflo** [comment] 2015-01-21 09:15
_From @derhasi on December 24, 2014 10:57_

@dutchiexl, currently there might be multiple reasons for missing or misconfigured packages. So collecting all of those would be a large help, so we might find more edge cases.

We might add functionality to the project in the future, so a composer.json within a drupal project may be recognized and can override some or all auto-generated information.

I try to add some information to the README soon.

**Comment by webflo** [comment] 2015-01-21 09:15
_From @derhasi on January 13, 2015 16:2_

I added the issue in drupal-composer/drupal-packagist. So we could close this here :)

**Comment by derhasi** [comment] 2015-01-21 09:42
Closed as duplicate of https://github.com/drupal-composer/drupal-packagist/issues/2

**Closed as completed by derhasi** 2015-01-21 09:42 UTC
Labels: duplicate
